apiVersion: apps/v1
kind: Deployment
metadata:
  name: book-catalog-deployment
  labels:
    app: book-catalog
spec:
  replicas: 1
  selector:
    matchLabels:
      app: book-catalog
  template:
    metadata:
      labels:
        app: book-catalog
    spec:
      containers:
      - name: book-catalog-container
        image: sit722week007.azurecr.io/book_catalog:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 5000
        env:
        - name: DATABASE_URL
          value: "postgresql://book_inventory_3ibf_user:Zk8jOO5cGkOpUuLHOD2ki0GL96LvIuCk@dpg-crnctn56l47c73adph5g-a.oregon-postgres.render.com/book_inventory_3ibf"

---
apiVersion: v1
kind: Service
metadata:
  name: book-catalog-service
spec:
  type: LoadBalancer
  selector:
    app: book-catalog
  ports:
  - protocol: TCP
    port: 5000
    targetPort: 5000
    

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: inventory-management-deployment
  labels:
    app: inventory-management
spec:
  replicas: 1
  selector:
    matchLabels:
      app: inventory-management
  template:
    metadata:
      labels:
        app: inventory-management
    spec:
      containers:
      - name: inventory-management-container
        image: sit722week007.azurecr.io/inventory_management:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 5001
        env:
        - name: DATABASE_URL
          value: "postgresql://book_inventory_3ibf_user:Zk8jOO5cGkOpUuLHOD2ki0GL96LvIuCk@dpg-crnctn56l47c73adph5g-a.oregon-postgres.render.com/book_inventory_3ibf"

---
apiVersion: v1
kind: Service
metadata:
  name: inventory-management-service
spec:
  type: LoadBalancer
  selector:
    app: inventory-management
  ports:
  - protocol: TCP
    port: 5001
    targetPort: 5001
